---
- name: cinder control plane
  gather_facts: force
  hosts: controller
  roles:
    - role: cinder-control
      tags: ['openstack', 'cinder', 'control', 'ceph']
      when: cinder.enabled|bool
  environment: "{{ env_vars|default({}) }}"

- name: cinder data plane
  gather_facts: force
  hosts: cinder_volume
  roles:
    - role: cinder-data
      tags: ['openstack', 'cinder', 'data', 'cinder-data', 'ceph']
      when: cinder.enabled|bool
  environment: "{{ env_vars|default({}) }}"
