---
- name: swift code and config
  gather_facts: force
  hosts: swiftnode
  gather_facts: force
  roles:
    - role: haproxy
      haproxy_type: swift
      tags: ['openstack', 'swift', 'control', 'haproxy', 'infra']
    - role: swift-object
      tags: ['openstack', 'swift', 'swift-object', 'data']
    - role: swift-account
      tags: ['openstack', 'swift', 'data']
    - role: swift-container
      tags: ['openstack', 'swift', 'data']
    - role: swift-proxy
      tags: ['openstack', 'swift', 'control']
  environment: "{{ env_vars|default({}) }}"

- name: swift bootstrap rings
  hosts: swiftnode_primary
  roles:
    - role: swift-ring
      tags: ['openstack', 'swift', 'swift-ring', 'data']
  environment: "{{ env_vars|default({}) }}"
