---
dependencies:
  - role: endpoints
  - role: apt-repos
  - role: monitoring-common
    when: monitoring.enabled|default(True)|bool
  - role: logging-config
    when: logging.enabled|default(True)|bool
    service: neutron
    logdata: "{{ neutron.logs }}"
  - role: openstack-source
    project_name: "{{ project_name }}"
    project_rev: "{{ neutron.source.rev }}"
    rootwrap: True
    alternatives: "{{ neutron.alternatives }}"
    system_dependencies: "{{ neutron.source.system_dependencies }}"
    python_dependencies: "{{ neutron.source.python_dependencies }}"
    when: openstack_install_method == 'source'
  - role: openstack-package
    project_name: "{{ project_name }}"
    rootwrap: True
    alternatives: "{{ neutron.alternatives }}"
    when: openstack_install_method == 'package'
