---
- name: restart aodh services
  service: name={{ item }} state=restarted
  failed_when: false
  when: restart|default('True')
  with_items:
    - aodh-api
    - aodh-evaluator
    - aodh-listener
    - aodh-notifier
