---
- name: check nova
  shell: "curl -I --connect-timeout 2 {{ endpoints[item].url.public }} }}"
  with_items:
    - glance
    - keystone
    - neutron
    - nova
  delegate_to: localhost
  become: no
